import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../components/Header';
import Footer from '../components/Footer';
import Slider from '../components/Slider';
import DisplayCategoryCard from '../components/DisplayCategoryCard';
import { Assets } from '../../public/assets/Assets';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Agri Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    { name: 'Makeup', image: Assets.slider_img1 },
    { name: 'Makeup', image: Assets.slider_img1 },
    { name: 'Makeup', image: Assets.slider_img1 },
    { name: 'Makeup', image: Assets.slider_img1 }
  ];
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Slider />
        <DisplayCategoryCard items={items} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
